import { randomBytes, scryptSync } from "node:crypto";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const [username, password] = process.argv.slice(2);

if (!username || !password || password.length < 14 || !/^[A-Za-z0-9._-]{3,64}$/.test(username)) {
  console.error("Usage: npm run setup-admin -- <username-with-letters-numbers-dot-dash-or-underscore> <password-with-14-or-more-characters>");
  process.exit(1);
}

const salt = randomBytes(16).toString("hex");
const hash = scryptSync(password, salt, 64).toString("hex");
const target = resolve(".env");
const current = existsSync(target) ? readFileSync(target, "utf8") : "";
const retained = current
  .split(/\r?\n/)
  .filter((line) => !/^ADMIN_(USERNAME|PASSWORD_SALT|PASSWORD_HASH)=/.test(line))
  .join("\n")
  .trimEnd();
const credentials = [
  "# Admin credentials are generated by setup-admin.mjs. Do not commit this file.",
  `ADMIN_USERNAME=${username}`,
  `ADMIN_PASSWORD_SALT=${salt}`,
  `ADMIN_PASSWORD_HASH=${hash}`
].join("\n");
writeFileSync(target, `${retained ? `${retained}\n\n` : ""}${credentials}\n`, { mode: 0o600 });
console.log(`Admin account created for ${username}. Credentials are stored in .env, which Git ignores.`);
